### ISSUE TITLE
sls deploy error

### ISSUE THREAD

**Issue by bairock** [JetClosing/graphql-lambda-websocket#1]
The CloudFormation template is invalid: Template format error: Unrecognized resource types: [AWS::Lambda::LayerVersion] ??

serverless.yml

    
service: graphql-lambda-ws-example-basic-backend

plugins:
  - serverless-plugin-graphql-lambda-ws

custom:
  graphql-lambda-ws:
    schemaPath: './schema'

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello

**Comment by chris-feist** [comment]
@bairock it appears this is an AWS issue, possibly with the region you are deploying to. I've primarily been testing in `us-west-2`. Also ensure you are using a recent version of serverless, as the plugin is just using serverless to [define the lambda layer](https://serverless.com/framework/docs/providers/aws/guide/layers/) under the covers, which is still appears to be [correctly defined](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-layerversion.html).

Also note that this library is not production ready. It needs some improvements. It also doesn't work with the `serverless-webpack` plugin.

**Comment by bairock** [comment]
thank you. i will check

> @bairock, похоже, это проблема с AWS, возможно, в регионе, в который вы развертываете. Я в основном тестировал в `us-west-2`. Также убедитесь, что вы используете последнюю версию без сервера, так как плагин просто использует без сервера для [определения лямбда-слоя](https://serverless.com/framework/docs/providers/aws/guide/layers/) под крышками, который по-прежнему выглядит [правильно определенным](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-layerversion.html) .
> 
> Также обратите внимание, что эта библиотека не готова к работе. Нужны некоторые улучшения. Это также не работает с `serverle
